[package]
name = "buddyasm_tileset"
description = "Read images and convert them into optimized tilesets for retro consoles"
repository.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["binary"]

# dependencies enabled when building the binary
binary = ["dep:buddyasm_common"]

[[bin]]
name = "tileset"
required-features = ["binary"]


[dependencies]

# Report errors when loading images
thiserror.workspace = true

# Serialize & deserialize data
serde.workspace = true
serde_json = "1.0"

# Map enums with strings
strum = { version = "0.28", features = ["derive"] }

# Process matrix data
ndarray = { version = "0.17", features = ["rayon", "serde"] }
itertools = "0.14"

# Serialize the data into a contiguous sequence
bytes = "1.11"
bitfield = "0.19"
bitvec = "1.0"
bytemuck = "1.25"

# Load regular image formats
image = { version = "0.25", features = ["bmp", "png"] }

# Load Aseprite file
asefile = "0.3"

# Load Tiled file
tiled = "0.15"

# Generate source files from data processed
tera = { version = "2", features = ["fast"] }

# Binary dependencies
buddyasm_common = { path = "../common", optional = true }
