
[config]

# Target hardware
system = "famicom"

# Background or Foreground tileset
kind = "fg"

# Bitplane layout
bit_plane = "bpp2"

# Default palette to use for processing the spritework
default_palette = "palette.png"

# Where to output the processed tileset
output = "../../../output/anim"


[[entry]]

# Optional name for the entry
name = "splat"

# Load a sprite work
image = "animated.aseprite"

# Should we output the index data in JSON format
# Only applicable for static and animated spritework entries
output_json = true
