
[config]

# Target hardware
hardware = "megadrive"

# Background or Foreground tileset
kind = "bg"

# Default palette to use for processing the spritework
default_palette = "palette.png"

# Where to output the processed tileset
output = "../../output/md"


[[entry]]

# Load a font file
image = "font_vincent.png"

# Pick all printable ASCII characters and place them at the expected location for ASCII characters
mapping = [ { start = 0x20, end = 0x7F, target = 0x20 } ]

[[entry]]

# Load a sprite work
image = "title.png"

# Use a custom palette
palette = "palette-title.png"
