[package]
name = "buddyasm_text"
description = "Read paragraphs and re-encode them into matrices of bytes"
repository.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true


[features]
default = ["binary"]

# dependencies enabled when building the binary
binary = ["dep:clap"]

[[bin]]
name = "main"
required-features = ["binary"]


[dependencies]

buddyasm_common = { path = "../common" }

# Report errors when loading images
thiserror.workspace = true

# Serialize & deserialize data
serde.workspace = true

# Allow reformatting text so that it fits the target text box
textwrap = "0.16"
ndarray = { version = "0.17", features = ["rayon"] }

# Generate source files from data processed
tera = { version = "2", features = ["fast"] }


# Command-line arguments
clap = { version = "4.6", features = ["derive"], optional = true }
